name: Deploy

on:
  workflow_run:
    workflows: [Tests]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Development
        uses: actions/github-script@v6
        with:
          script: |
            console.log('Deploying application...')
            console.log('Deployment completed successfully!')
