name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Linting Check
        run: |
          if [[ "${{ secrets.LINT_SHOULD_PASS }}" == "false" ]]; then
            echo "Lint check deliberately failed based on secret configuration."
            exit 1
          else
            node ./scripts/lint.js
          fi

