name: Tests

on:
  workflow_run:
    workflows: [Lint]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: |
          if [[ "${{ secrets.TEST_SHOULD_PASS }}" == "false" ]]; then
            echo "Tests check deliberately failed based on secret configuration."
            exit 1
          fi


