name: Tests

on:
  workflow_run:
    workflows: [Lint]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        uses: actions/github-script@v6
        with:
          script: |
            console.log('Running tests...')
            const testsPass = true;
            if (!testsPass) {
              console.log('Tests failed!');
              process.exit(1);
            }
            console.log('Tests completed successfully!')
