name: Tests

on:
  workflow_run:
    workflows: [Lint]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: node ./scripts/test.js
        env:
          # Change to 'false' to simulate failing tests
          TESTS_SHOULD_PASS: 'true'

